language: objective-c

osx_image: xcode7.1
xcode_project: appledoc.xcodeproj
xcode_scheme: appledoc
xcode_sdk: macosx10.10

before_script:
- gem install xcpretty

script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- xctool test -scheme tests -sdk "macosx10.10" -destination "arch=x86_64" -configuration Debug
